const ACCOUNT = {
  FETCH: "ACCOUNT_FETCH",
  FETCH_ERROR: "ACCOUNT_FETCH_ERROR",
  FETCH_SUCCESS: "ACCOUNT_FETCH_SUCCESS",
};
const ACCOUNT_INFO = {
  FETCH: "ACCOUNT_INFO_FETCH",
  FETCH_ERROR: "ACCOUNT_INFO_FETCH_ERROR",
  FETCH_SUCCESS: "ACCOUNT_INFO_FETCH_SUCCESS",
};
export { ACCOUNT, ACCOUNT_INFO };
